<a href="https://colab.research.google.com/github/Gudepushruthi-2006/Spam-Email-Classifier/blob/main/Spam_Email_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Shruthi")

Hello Shruthi

In [ ]:
11a=10
b=5
print(a+b)

15

In [ ]:
!pip install scikit-learn pandas numpy

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

data = {
    "text": [
        "Win a free lottery now",
        "Hi Shruthi, how are you?",
        "Claim your free prize today",
        "Let's meet tomorrow",
        "Congratulations you won money"
    ],
    "label": ["spam", "ham", "spam", "ham", "spam"]
}

df = pd.DataFrame(data)
df

                            text label
0         Win a free lottery now  spam
1       Hi Shruthi, how are you?   ham
2    Claim your free prize today  spam
3            Let's meet tomorrow   ham
4  Congratulations you won money  spam

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["text"])

print(X.toarray())

[[0.         0.         0.         0.42224214 0.         0.
  0.         0.52335825 0.         0.         0.52335825 0.
  0.         0.         0.         0.52335825 0.         0.
  0.        ]
 [0.46369322 0.         0.         0.         0.46369322 0.46369322
  0.         0.         0.         0.         0.         0.
  0.46369322 0.         0.         0.         0.         0.37410477
  0.        ]
 [0.         0.46369322 0.         0.37410477 0.         0.
  0.         0.         0.         0.         0.         0.46369322
  0.         0.46369322 0.         0.         0.         0.
  0.46369322]
 [0.         0.         0.         0.         0.         0.
  0.57735027 0.         0.57735027 0.         0.         0.
  0.         0.         0.57735027 0.         0.         0.
  0.        ]
 [0.         0.         0.52335825 0.         0.         0.
  0.         0.         0.         0.52335825 0.         0.
  0.         0.         0.         0.         0.52335825 0.42224214
  0.        ]]

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X, df["label"])

print("Model trained successfully")

Model trained successfully

In [ ]:
new_message = ["Congratulations! You won a free ticket"]

new_message_vector = vectorizer.transform(new_message)

prediction = model.predict(new_message_vector)

print("Prediction:", prediction[0])

Prediction: spam

In [ ]:
new_message = ["Hi Shruthi, shall we meet tomorrow?"]
new_message_vector=vectorizer.transform(new_message)
prediction=model.predict(new_message_vector)
print("Prediction:",prediction[0])

Prediction: ham

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

df = pd.read_csv(url, sep='\t', header=None, names=["label", "text"])

df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.shape

(5572, 2)

In [ ]:
df["label"] = df["label"].map({"ham": 0, "spam": 1})

df.head()

   label                                               text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X = df["text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Data split successfully")

Data split successfully

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_tfidf, y_train)

print("Model trained on real dataset")

Model trained on real dataset

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.9668161434977578

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[966   0]
 [ 37 112]]